"""empty message

Revision ID: 1fb4c2d60a43
Revises: 
Create Date: 2021-03-23 21:49:45.118985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb4c2d60a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('year', sa.String(length=120), nullable=True),
    sa.Column('director', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('character_type', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['Movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Actor')
    op.drop_table('Movie')
    # ### end Alembic commands ###
